### ISSUE TITLE
Installing problem

### ISSUE THREAD

**Issue by tooanri4you** [KurozeroPB/discotify#1]
Git has not been found. I use Windows 10

**Comment by Pepijn98** [comment]
Then install git https://www.atlassian.com/git/tutorials/install-git#windows

**Comment by tooanri4you** [comment]
Ok... I installed discotify now and i have an error like this. Don't worry if it's unfixable. I only wanted to test this on windows 10. https://i.imgur.com/0Eb30ow.png

**Comment by Pepijn98** [comment]
Which node version are you using? Check with `node -v`, discotify requires node version >= 8.

**Comment by tooanri4you** [comment]
Oh i was using 6.11.3. I'm going to install the newer version.

**Comment by tooanri4you** [comment]
Thank you! https://i.imgur.com/4CZpdGc.png

**Comment by tooanri4you** [comment]
Works perfect! https://i.imgur.com/MH2jCMT.png

**Comment by tooanri4you** [comment]
Add in the description the tested OS

**Comment by Pepijn98** [comment]
Oke thanks for testing 👍

**Comment by tooanri4you** [comment]
Close the issue if you want.
